### ISSUE TITLE
Ask for permisson of including this repo in Taichi's official demos

### ISSUE THREAD

**Issue by neozhaoliang** [hietwll/LBM_Taichi#6]
@hietwll  Hi, thank you for this great project. Our Taichi development team thinks this project is great and hopes to include it in Taichi's official demos:  https://github.com/taichi-dev/taichi/tree/master/python/taichi/examples
We may probably modify the code a bit (for formatting and GUI event handling reasons) and credit the example to you. Looking for your permission!

**Comment by hietwll** [comment]
yes, of course you could use/modify it. it's my hornor to have this demo included in Taichi's official repo :)

**Comment by neozhaoliang** [comment]
Thanks!
