### ISSUE TITLE
Compile error with latest Taichi1.60

### ISSUE THREAD

**Issue by sutongkui** [hietwll/LBM_Taichi#7]
[Taichi] version 1.6.0, llvm 15.0.1, commit f1c6fbbd, win, python 3.8.3
[Taichi] Starting on arch=cuda
Traceback (most recent call last):
  File ".\lbm_solver.py", line 185, in <module>
    lbm.solve()
  File ".\lbm_solver.py", line 154, in solve
    self.apply_bc()
  File "D:\Dev\Anaconda3\lib\site-packages\taichi\lang\kernel_impl.py", line 1035, in __call__
    raise type(e)("\n" + str(e)) from None
taichi.lang.exception.TaichiSyntaxError:
File ".\lbm_solver.py", line 101, in apply_bc:
        for j in ti.ndrange(1, self.ny - 1):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            # left: dr = 0; ibc = 0; jbc = j; inb = 1; jnb = j
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Ndrange for loop with number of the loop variables not equal to the dimension of the ndrange is not supported. Please check if the number of arguments of ti.ndrange() is equal to the number of the loop variables.

Which version of Taichi is supported?

**Comment by hietwll** [comment]
it should now support latest taichi version (1.6.0), try `python lbm_solver.py 0`.
